
import junit.framework.Test; 
import junit.framework.TestSuite; 

public class ParkingChargesTestSuite
{
	//Builds the test suite.
	/****************************************************
	* Method     : Test suite
	*
	* Purpose    : Builds the test suite and adds the ParkingChargesTest.class to it
	* 
	* Parameters : N/A
	*
	* Returns    : returns the results generated by the assertion statements in ParkingChargesTest.class			
	****************************************************/		
	public static Test suite() 
	{ 
		TestSuite suite = new TestSuite(); 
		
		suite.addTestSuite( ParkingChargesTest.class );
		
		return suite; 
	}
	 
	/****************************************************
	* Method     : Main
	*
	* Purpose    : Instantiates and runs the Test suite.
	* 
	* Parameters : N/A
	*
	* Returns    : N/A
	*****************************************************/
	public static void main(String[] args) 
	{ 
		junit.textui.TestRunner.run(suite());
	} 
	
} 