/********************************************************
*  Project :  Assignment 07 - Palindromes
*  File    :  PalindromeTestSuite.java
*  Name    :  Anthony Browness
*  Date    :  7/03/2013
*
*  Description : 
*
*    1) Purpose: Builds and runs the Palindromes Test Suite.
*     
*    2) Data-structures: N/A
*
*    3) Data-structure- Algorithms, Techniques, Implementations: N/A
*
*    4) Methods: main, suite 
*
*  Changes : N/A
********************************************************/

import junit.framework.Test;
import junit.framework.TestSuite;


public class PalindromeTestSuite
{
		//Builds the test suite.
		/****************************************************
		* Method     : Test suite
		*
		* Purpose    : Builds the test suite and adds the PalindromeTest.class to it
		* 
		* Parameters : N/A
		*
		* Returns    : returns the results generated by the assertion statements in 
		* 				PalindromeTest.class			
		****************************************************/		
		public static Test suite() 
		{ 
			TestSuite suite = new TestSuite(); 
			
			suite.addTestSuite( PalindromeTest.class );
			
			return suite; 
		}
		 
		/****************************************************
		* Method     : Main
		*
		* Purpose    : Instantiates and runs the Test suite.
		* 
		* Parameters : N/A
		*
		* Returns    : N/A
		*****************************************************/
		public static void main(String[] args) 
		{ 
			junit.textui.TestRunner.run(suite());
		} 
		
	} 