/**
 * Project: Assignment 3b - Stack Implementations
 * Authors: Anthony Browness, Jake Brinkerhoff
 */

import junit.framework.Test;
import junit.framework.TestSuite;


public class StackTestSuite
{
		//Builds the test suite.
		/****************************************************
		* Method     : Test suite
		*
		* Purpose    : Builds the test suite and adds the StackTest.class to it
		* 
		* Parameters : N/A
		*
		* Returns    : returns the results generated by the assertion statements in Stack.class			
		****************************************************/		
		public static Test suite() 
		{ 
			TestSuite suite = new TestSuite(); 
			
			suite.addTestSuite( StackTest.class );
			
			return suite; 
		}
		 
		/****************************************************
		* Method     : Main
		*
		* Purpose    : Instantiates and runs the Test suite.
		* 
		* Parameters : N/A
		*
		* Returns    : N/A
		*****************************************************/
		public static void main(String[] args) 
		{ 
			junit.textui.TestRunner.run(suite());
		} 
		
	} 